ccflags-y += -I$(srctree)/drivers/misc/mediatek/hwmon/include
ccflags-y += -I$(srctree)/drivers/misc/mediatek/pick_up_sensor/inc
ccflags-y += -I$(srctree)/drivers/misc/mediatek/pick_up_sensor
obj-y	:=  mpu6050.o

