# In case the platform does NOT support this type of sensors
ccflags-y += -I$(srctree)/drivers/misc/mediatek/hwmon/include


#obj-y += gn_device_check.o
#Gionee BSP1 lihl  modify for  device_check start
obj-$(CONFIG_GN_BSP_MTK_DEVICE_CHECK) +=gn_device_check.o
#Gionee BSP1 lihl  modify for  device_check end